import type { ApplicationModel, Model } from '@gstack/application';

import type { GeneratedArtifactInput } from './artifact.js';

export function generateAiDocumentationArtifacts(
  application: ApplicationModel,
): readonly GeneratedArtifactInput[] {
  return Object.freeze([agentsArtifact(), contextArtifact(application)]);
}

function agentsArtifact(): GeneratedArtifactInput {
  return Object.freeze({
    path: 'generated/ai/AGENTS.md',
    content: `# Generated AI Context Rules

This directory is generated by gstack. Do not edit files here manually.

- Treat the gstack Schema and normalized Application Model as the source of truth.
- Do not store or add secrets, credentials, tokens, or passwords.
- Do not infer or execute destructive operations from this context.
- Do not copy inferred behavior into manual code under app/ or custom/.
- Regenerate this context after changing the Schema.
`,
  });
}

function contextArtifact(
  application: ApplicationModel,
): GeneratedArtifactInput {
  const models = [...application.models].sort((left, right) =>
    left.name.localeCompare(right.name),
  );
  return Object.freeze({
    path: 'generated/ai/PROJECT_CONTEXT.md',
    content: [
      '<!-- This file was generated by gstack. DO NOT EDIT. -->',
      '',
      '# gstack Project Context',
      '',
      `Application: ${inline(application.name)}`,
      `Schema Version: ${application.schemaVersion}`,
      '',
      ...(models.length === 0
        ? ['Models: none', '']
        : models.flatMap(modelContext)),
    ].join('\n'),
  });
}

function modelContext(model: Model): readonly string[] {
  const fields = [...model.fields]
    .sort((left, right) => left.name.localeCompare(right.name))
    .map(
      (field) =>
        `- ${inline(field.name)}: ${field.type}${field.required ? ', required' : ', optional'}${field.unique ? ', unique' : ''}`,
    );
  const relations = [...model.relations]
    .sort((left, right) => left.name.localeCompare(right.name))
    .map(
      (relation) =>
        `- ${inline(relation.name)}: ${relation.type} via ${inline(relation.field)} -> ${inline(relation.targetModel)}.${inline(relation.references)}`,
    );
  return [
    `## ${heading(model.name)}`,
    '',
    `Primary Key: ${inline(model.primaryKey)}`,
    `API: ${api(model)}`,
    `UI list: ${list(model.ui.list.columns)}`,
    `UI form: ${list(model.ui.form.fields)}`,
    `Permissions: read=${list(model.permissions.read)}; create=${list(model.permissions.create)}; update=${list(model.permissions.update)}; delete=${list(model.permissions.delete)}`,
    `Workflow: ${model.workflow.enabled ? 'enabled' : 'disabled'}`,
    `Events: ${model.events.enabled ? 'enabled' : 'disabled'}`,
    '',
    '### Fields',
    '',
    ...(fields.length === 0 ? ['- none'] : fields),
    '',
    '### Relations',
    '',
    ...(relations.length === 0 ? ['- none'] : relations),
    '',
  ];
}

function api(model: Model): string {
  if (model.api.resource === null) return 'disabled';
  return `${inline(model.api.resource)} [list${model.api.create ? ', create' : ''}${model.api.update ? ', update' : ''}${model.api.delete ? ', delete' : ''}]`;
}

function list(values: readonly string[]): string {
  return values.length === 0
    ? 'none'
    : [...values].sort().map(inline).join(', ');
}

function inline(value: string): string {
  return `\`${value.replaceAll('`', '\\`').replaceAll('\n', ' ')}\``;
}

function heading(value: string): string {
  return value
    .replaceAll('\\', '\\\\')
    .replaceAll('#', '\\#')
    .replaceAll('\n', ' ');
}
