import type { ApplicationModel, Model } from '@gstack/application';

import type { GeneratedArtifactInput } from './artifact.js';
import { typescriptTypeName } from './typescript.js';

const HEADER = '// This file was generated by gstack. DO NOT EDIT.\n\n';

export function generateApiArtifact(
  application: ApplicationModel,
): GeneratedArtifactInput {
  const models = [...application.models]
    .filter(({ api }) => api.resource !== null)
    .sort((left, right) => left.name.localeCompare(right.name));
  const imports = models
    .map(
      (model) =>
        `import type { ${typescriptTypeName(model.name)} } from '../types/${model.name}.js';`,
    )
    .join('\n');
  const routes = models.flatMap(modelRoutes).join(',\n');
  return Object.freeze({
    path: 'generated/api/contracts.ts',
    content: `${HEADER}${imports}${imports ? '\n\n' : ''}export interface ApiRoute<Request, Response> {
  readonly method: 'GET' | 'POST' | 'PATCH' | 'DELETE';
  readonly path: string;
  readonly operationId: string;
  readonly _request?: Request;
  readonly _response?: Response;
}

export const apiRoutes = [
${routes}
] as const;
`,
  });
}

function modelRoutes(model: Model): readonly string[] {
  const name = typescriptTypeName(model.name);
  const resource = model.api.resource!;
  return [
    route('GET', `/${resource}`, `list${name}`, 'void', `readonly ${name}[]`),
    ...(model.api.create
      ? [route('POST', `/${resource}`, `create${name}`, name, name)]
      : []),
    ...(model.api.update
      ? [
          route(
            'PATCH',
            `/${resource}/{${model.primaryKey}}`,
            `update${name}`,
            `Partial<${name}>`,
            name,
          ),
        ]
      : []),
    ...(model.api.delete
      ? [
          route(
            'DELETE',
            `/${resource}/{${model.primaryKey}}`,
            `delete${name}`,
            'void',
            'void',
          ),
        ]
      : []),
  ];
}

function route(
  method: string,
  path: string,
  operationId: string,
  request: string,
  response: string,
): string {
  return `  { method: ${JSON.stringify(method)}, path: ${JSON.stringify(path)}, operationId: ${JSON.stringify(operationId)} } satisfies ApiRoute<${request}, ${response}>`;
}
