import type { ApplicationModel } from '@gstack/application';

import type { GeneratedArtifactInput } from './artifact.js';

const PREFIX = 'generated/backend/appsscript/';

export function generateAppsScriptBackendArtifacts(
  application: ApplicationModel,
): readonly GeneratedArtifactInput[] {
  const models = [...application.models]
    .sort((left, right) => left.name.localeCompare(right.name))
    .map((model) => ({
      model: model.name,
      resource: model.api.resource!,
      primaryKey: model.primaryKey,
      fields: [...model.fields].map(({ name }) => name),
      required: [...model.fields]
        .filter(({ required }) => required)
        .map(({ name }) => name),
      rules: [...model.fields].map((field) => ({
        name: field.name,
        type: field.type,
        required: field.required,
        unique: field.unique,
        enumValues: field.enumValues,
        validation: field.validation,
      })),
      indexes: [...model.indexes]
        .sort((left, right) => left.name.localeCompare(right.name))
        .map((index) => ({
          name: index.name,
          columns: [...index.columns],
          unique: index.unique,
        })),
      relations: [...model.relations]
        .sort((left, right) => left.name.localeCompare(right.name))
        .map((relation) => ({
          name: relation.name,
          field: relation.field,
          targetModel: relation.targetModel,
          references: relation.references,
        })),
      create: model.api.create,
      update: model.api.update,
      delete: model.api.delete,
    }));
  return Object.freeze([
    Object.freeze({
      path: `${PREFIX}appsscript.json`,
      content: `${JSON.stringify(
        {
          timeZone: 'Etc/UTC',
          dependencies: {},
          exceptionLogging: 'STACKDRIVER',
          runtimeVersion: 'V8',
          webapp: { access: 'MYSELF', executeAs: 'USER_DEPLOYING' },
        },
        null,
        2,
      )}\n`,
    }),
    Object.freeze({
      path: `${PREFIX}main.gs`,
      content: runtimeSource(models),
    }),
  ]);
}

function runtimeSource(models: readonly object[]): string {
  return `// This file was generated by gstack. DO NOT EDIT.
const GSTACK_MODELS = ${JSON.stringify(models)};

function doGet(event) {
  return gstackHandle_('GET', event);
}

function doPost(event) {
  const method = String((event.parameter || {}).__gstack_method || 'POST').toUpperCase();
  return gstackHandle_(method, event);
}

function gstackHandle_(method, event) {
  try {
    const parts = String(event.pathInfo || '').split('/').filter(Boolean);
    const definition = GSTACK_MODELS.find(function (item) { return item.resource === parts[0]; });
    if (!definition) return gstackJson_({ ok: false, error: { code: 'RESOURCE_NOT_FOUND' } });
    if (method === 'GET' && parts.length === 1) return gstackJson_({ ok: true, data: gstackList_(definition) });
    if (method === 'POST' && parts.length === 1 && definition.create) return gstackJson_({ ok: true, data: gstackCreate_(definition, gstackBody_(event)) });
    if (method === 'PATCH' && parts.length === 2 && definition.update) return gstackJson_({ ok: true, data: gstackUpdate_(definition, parts[1], gstackBody_(event)) });
    if (method === 'DELETE' && parts.length === 2 && definition.delete) { gstackDelete_(definition, parts[1]); return gstackJson_({ ok: true, data: null }); }
    return gstackJson_({ ok: false, error: { code: 'OPERATION_NOT_ALLOWED' } });
  } catch (error) {
    const code = error && error.message === 'NOT_FOUND' ? 'RECORD_NOT_FOUND'
      : error && error.message === 'REFERENCE_CONFLICT' ? 'CONFLICT'
      : 'REQUEST_INVALID';
    return gstackJson_({ ok: false, error: { code: code } });
  }
}

function gstackSheet_(definition) {
  const sheet = SpreadsheetApp.openById(GSTACK_SPREADSHEET_ID).getSheetByName(definition.model);
  if (!sheet) throw new Error('NOT_FOUND');
  return sheet;
}

function gstackRows_(definition) {
  const values = gstackSheet_(definition).getDataRange().getValues();
  const header = values.shift() || [];
  if (JSON.stringify(header) !== JSON.stringify(definition.fields)) throw new Error('DRIFT');
  return { header: header, rows: values };
}

function gstackList_(definition) {
  const table = gstackRows_(definition);
  return table.rows.filter(function (row) { return row.some(function (value) { return value !== ''; }); }).map(function (row) {
    return Object.fromEntries(table.header.map(function (name, index) { return [name, row[index]]; }));
  });
}

function gstackCreate_(definition, body) {
  const record = gstackRecord_(definition, body, false);
  const lock = LockService.getScriptLock();
  lock.waitLock(30000);
  try {
    const existing = gstackList_(definition);
    gstackUnique_(definition, existing, record, null);
    gstackRelations_(definition, record);
    gstackSheet_(definition).appendRow(definition.fields.map(function (name) { return record[name] === undefined ? '' : record[name]; }));
  } finally { lock.releaseLock(); }
  return record;
}

function gstackUpdate_(definition, key, body) {
  const changes = gstackRecord_(definition, body, true);
  if (Object.prototype.hasOwnProperty.call(changes, definition.primaryKey) && String(changes[definition.primaryKey]) !== key) throw new Error('INVALID');
  const lock = LockService.getScriptLock();
  lock.waitLock(30000);
  try {
    const sheet = gstackSheet_(definition);
    const table = gstackRows_(definition);
    const keyIndex = table.header.indexOf(definition.primaryKey);
    const rowIndex = table.rows.findIndex(function (row) { return String(row[keyIndex]) === key; });
    if (rowIndex < 0) throw new Error('NOT_FOUND');
    const current = Object.fromEntries(table.header.map(function (name, index) { return [name, table.rows[rowIndex][index]]; }));
    Object.keys(changes).forEach(function (name) { current[name] = changes[name]; });
    const existing = table.rows.map(function (row) { return Object.fromEntries(table.header.map(function (name, index) { return [name, row[index]]; })); });
    gstackUnique_(definition, existing, current, rowIndex);
    gstackRelations_(definition, current);
    sheet.getRange(rowIndex + 2, 1, 1, table.header.length).setValues([table.header.map(function (name) { return current[name]; })]);
    return current;
  } finally { lock.releaseLock(); }
}

function gstackDelete_(definition, key) {
  const lock = LockService.getScriptLock();
  lock.waitLock(30000);
  try {
    const sheet = gstackSheet_(definition);
    const table = gstackRows_(definition);
    const keyIndex = table.header.indexOf(definition.primaryKey);
    const rowIndex = table.rows.findIndex(function (row) { return String(row[keyIndex]) === key; });
    if (rowIndex < 0) throw new Error('NOT_FOUND');
    const current = Object.fromEntries(table.header.map(function (name, index) { return [name, table.rows[rowIndex][index]]; }));
    gstackRestrictDelete_(definition, current, rowIndex);
    sheet.deleteRow(rowIndex + 2);
  } finally { lock.releaseLock(); }
}

function gstackRecord_(definition, body, partial) {
  if (!body || typeof body !== 'object' || Array.isArray(body)) throw new Error('INVALID');
  const keys = Object.keys(body);
  if (keys.some(function (name) { return definition.fields.indexOf(name) < 0; })) throw new Error('INVALID');
  if (!partial && definition.required.some(function (name) { return !Object.prototype.hasOwnProperty.call(body, name); })) throw new Error('INVALID');
  definition.rules.forEach(function (rule) {
    if (Object.prototype.hasOwnProperty.call(body, rule.name) && !gstackValueValid_(rule, body[rule.name])) throw new Error('INVALID');
  });
  return body;
}

function gstackValueValid_(rule, value) {
  if (value === null) return !rule.required;
  if (value === undefined) return !rule.required;
  let valid = false;
  if (rule.type === 'string' || rule.type === 'text') valid = typeof value === 'string';
  if (rule.type === 'uuid') valid = typeof value === 'string' && /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
  if (rule.type === 'integer') valid = typeof value === 'number' && Number.isSafeInteger(value);
  if (rule.type === 'number') valid = typeof value === 'number' && Number.isFinite(value);
  if (rule.type === 'boolean') valid = typeof value === 'boolean';
  if (rule.type === 'date') valid = typeof value === 'string' && /^\\d{4}-\\d{2}-\\d{2}$/.test(value) && !Number.isNaN(Date.parse(value + 'T00:00:00Z'));
  if (rule.type === 'datetime') valid = typeof value === 'string' && !Number.isNaN(Date.parse(value));
  if (rule.type === 'json') valid = true;
  if (rule.type === 'enum') valid = typeof value === 'string' && rule.enumValues.indexOf(value) >= 0;
  if (!valid) return false;
  if (typeof value === 'string') {
    if (rule.validation.minLength !== null && value.length < rule.validation.minLength) return false;
    if (rule.validation.maxLength !== null && value.length > rule.validation.maxLength) return false;
    if (rule.validation.pattern !== null && !new RegExp(rule.validation.pattern).test(value)) return false;
  }
  if (typeof value === 'number') {
    if (rule.validation.min !== null && value < rule.validation.min) return false;
    if (rule.validation.max !== null && value > rule.validation.max) return false;
  }
  return true;
}

function gstackUnique_(definition, existing, record, excludedIndex) {
  definition.rules.filter(function (rule) { return rule.unique; }).forEach(function (rule) {
    if (!Object.prototype.hasOwnProperty.call(record, rule.name)) return;
    if (record[rule.name] === null || record[rule.name] === '') return;
    if (existing.some(function (item, index) {
      return index !== excludedIndex && String(item[rule.name]) === String(record[rule.name]);
    })) throw new Error('DUPLICATE');
  });
  definition.indexes.filter(function (index) { return index.unique; }).forEach(function (index) {
    if (index.columns.some(function (name) { return !Object.prototype.hasOwnProperty.call(record, name) || record[name] === null || record[name] === undefined || record[name] === ''; })) return;
    if (existing.some(function (item, itemIndex) {
      return itemIndex !== excludedIndex && index.columns.every(function (name) { return item[name] === record[name]; });
    })) throw new Error('DUPLICATE');
  });
}

function gstackRelations_(definition, record) {
  definition.relations.forEach(function (relation) {
    const value = record[relation.field];
    if (value === null || value === undefined || value === '') return;
    const target = GSTACK_MODELS.find(function (item) { return item.model === relation.targetModel; });
    if (!target) throw new Error('DRIFT');
    if (!gstackList_(target).some(function (item) { return item[relation.references] === value; })) throw new Error('REFERENCE_MISSING');
  });
}

function gstackRestrictDelete_(definition, record, deletedIndex) {
  GSTACK_MODELS.forEach(function (source) {
    source.relations.filter(function (relation) { return relation.targetModel === definition.model; }).forEach(function (relation) {
      const value = record[relation.references];
      if (value === null || value === undefined || value === '') return;
      if (gstackList_(source).some(function (item, itemIndex) {
        return !(source.model === definition.model && itemIndex === deletedIndex) && item[relation.field] === value;
      })) throw new Error('REFERENCE_CONFLICT');
    });
  });
}

function gstackBody_(event) {
  return JSON.parse((event.postData || {}).contents || '{}');
}

function gstackJson_(value) {
  return ContentService.createTextOutput(JSON.stringify(value)).setMimeType(ContentService.MimeType.JSON);
}
`;
}
