import type { ApplicationModel } from '@gstack/application';

import type { GeneratedArtifactInput } from './artifact.js';

const PREFIX = 'generated/backend/appsscript/';

export function generateAppsScriptBackendArtifacts(
  application: ApplicationModel,
): readonly GeneratedArtifactInput[] {
  const models = [...application.models]
    .filter(({ api }) => api.resource !== null)
    .sort((left, right) => left.name.localeCompare(right.name))
    .map((model) => ({
      model: model.name,
      resource: model.api.resource!,
      primaryKey: model.primaryKey,
      fields: [...model.fields].map(({ name }) => name),
      required: [...model.fields]
        .filter(({ required }) => required)
        .map(({ name }) => name),
      create: model.api.create,
      update: model.api.update,
      delete: model.api.delete,
    }));
  return Object.freeze([
    Object.freeze({
      path: `${PREFIX}appsscript.json`,
      content: `${JSON.stringify(
        {
          timeZone: 'Etc/UTC',
          dependencies: {},
          exceptionLogging: 'STACKDRIVER',
          runtimeVersion: 'V8',
          webapp: { access: 'MYSELF', executeAs: 'USER_DEPLOYING' },
        },
        null,
        2,
      )}\n`,
    }),
    Object.freeze({
      path: `${PREFIX}main.gs`,
      content: runtimeSource(models),
    }),
  ]);
}

function runtimeSource(models: readonly object[]): string {
  return `// This file was generated by gstack. DO NOT EDIT.
const GSTACK_MODELS = ${JSON.stringify(models)};

function doGet(event) {
  return gstackHandle_('GET', event);
}

function doPost(event) {
  const method = String((event.parameter || {}).__gstack_method || 'POST').toUpperCase();
  return gstackHandle_(method, event);
}

function gstackHandle_(method, event) {
  try {
    const parts = String(event.pathInfo || '').split('/').filter(Boolean);
    const definition = GSTACK_MODELS.find(function (item) { return item.resource === parts[0]; });
    if (!definition) return gstackJson_({ ok: false, error: { code: 'RESOURCE_NOT_FOUND' } });
    if (method === 'GET' && parts.length === 1) return gstackJson_({ ok: true, data: gstackList_(definition) });
    if (method === 'POST' && parts.length === 1 && definition.create) return gstackJson_({ ok: true, data: gstackCreate_(definition, gstackBody_(event)) });
    if (method === 'PATCH' && parts.length === 2 && definition.update) return gstackJson_({ ok: true, data: gstackUpdate_(definition, parts[1], gstackBody_(event)) });
    if (method === 'DELETE' && parts.length === 2 && definition.delete) { gstackDelete_(definition, parts[1]); return gstackJson_({ ok: true, data: null }); }
    return gstackJson_({ ok: false, error: { code: 'OPERATION_NOT_ALLOWED' } });
  } catch (error) {
    return gstackJson_({ ok: false, error: { code: error && error.message === 'NOT_FOUND' ? 'RECORD_NOT_FOUND' : 'REQUEST_INVALID' } });
  }
}

function gstackSheet_(definition) {
  const sheet = SpreadsheetApp.openById(GSTACK_SPREADSHEET_ID).getSheetByName(definition.model);
  if (!sheet) throw new Error('NOT_FOUND');
  return sheet;
}

function gstackRows_(definition) {
  const values = gstackSheet_(definition).getDataRange().getValues();
  const header = values.shift() || [];
  if (JSON.stringify(header) !== JSON.stringify(definition.fields)) throw new Error('DRIFT');
  return { header: header, rows: values };
}

function gstackList_(definition) {
  const table = gstackRows_(definition);
  return table.rows.filter(function (row) { return row.some(function (value) { return value !== ''; }); }).map(function (row) {
    return Object.fromEntries(table.header.map(function (name, index) { return [name, row[index]]; }));
  });
}

function gstackCreate_(definition, body) {
  const record = gstackRecord_(definition, body, false);
  const lock = LockService.getScriptLock();
  lock.waitLock(30000);
  try {
    const existing = gstackList_(definition);
    if (existing.some(function (item) { return String(item[definition.primaryKey]) === String(record[definition.primaryKey]); })) throw new Error('DUPLICATE');
    gstackSheet_(definition).appendRow(definition.fields.map(function (name) { return record[name] === undefined ? '' : record[name]; }));
  } finally { lock.releaseLock(); }
  return record;
}

function gstackUpdate_(definition, key, body) {
  const changes = gstackRecord_(definition, body, true);
  const lock = LockService.getScriptLock();
  lock.waitLock(30000);
  try {
    const sheet = gstackSheet_(definition);
    const table = gstackRows_(definition);
    const keyIndex = table.header.indexOf(definition.primaryKey);
    const rowIndex = table.rows.findIndex(function (row) { return String(row[keyIndex]) === key; });
    if (rowIndex < 0) throw new Error('NOT_FOUND');
    const current = Object.fromEntries(table.header.map(function (name, index) { return [name, table.rows[rowIndex][index]]; }));
    Object.keys(changes).forEach(function (name) { current[name] = changes[name]; });
    sheet.getRange(rowIndex + 2, 1, 1, table.header.length).setValues([table.header.map(function (name) { return current[name]; })]);
    return current;
  } finally { lock.releaseLock(); }
}

function gstackDelete_(definition, key) {
  const lock = LockService.getScriptLock();
  lock.waitLock(30000);
  try {
    const sheet = gstackSheet_(definition);
    const table = gstackRows_(definition);
    const keyIndex = table.header.indexOf(definition.primaryKey);
    const rowIndex = table.rows.findIndex(function (row) { return String(row[keyIndex]) === key; });
    if (rowIndex < 0) throw new Error('NOT_FOUND');
    sheet.deleteRow(rowIndex + 2);
  } finally { lock.releaseLock(); }
}

function gstackRecord_(definition, body, partial) {
  if (!body || typeof body !== 'object' || Array.isArray(body)) throw new Error('INVALID');
  const keys = Object.keys(body);
  if (keys.some(function (name) { return definition.fields.indexOf(name) < 0; })) throw new Error('INVALID');
  if (!partial && definition.required.some(function (name) { return !Object.prototype.hasOwnProperty.call(body, name); })) throw new Error('INVALID');
  return body;
}

function gstackBody_(event) {
  return JSON.parse((event.postData || {}).contents || '{}');
}

function gstackJson_(value) {
  return ContentService.createTextOutput(JSON.stringify(value)).setMimeType(ContentService.MimeType.JSON);
}
`;
}
