import type { ApplicationModel, Model } from '@gstack/application';

import type { GeneratedArtifactInput } from './artifact.js';

export function generateDocumentationArtifact(
  application: ApplicationModel,
): GeneratedArtifactInput {
  const models = [...application.models].sort((left, right) =>
    left.name.localeCompare(right.name),
  );
  const content = [
    '<!-- This file was generated by gstack. DO NOT EDIT. -->',
    '',
    `# ${heading(application.name)} Models`,
    '',
    ...(models.length === 0
      ? ['Modelはありません。', '']
      : models.flatMap(modelSection)),
  ].join('\n');
  return Object.freeze({ path: 'generated/docs/models.md', content });
}

function modelSection(model: Model): readonly string[] {
  const fields = [...model.fields].sort((left, right) =>
    left.name.localeCompare(right.name),
  );
  const indexes = [...model.indexes].sort((left, right) =>
    left.name.localeCompare(right.name),
  );
  const relations = [...model.relations].sort((left, right) =>
    left.name.localeCompare(right.name),
  );
  return [
    `## ${heading(model.displayName)}（${heading(model.name)}）`,
    '',
    model.description ? text(model.description) : '説明はありません。',
    '',
    `Primary Key: \`${code(model.primaryKey)}\``,
    '',
    '### Fields',
    '',
    ...(fields.length === 0
      ? ['なし', '']
      : [
          '| Name | Type | Required | Unique | Enum |',
          '| --- | --- | --- | --- | --- |',
          ...fields.map(
            (field) =>
              `| ${cell(field.name)} | ${cell(field.type)} | ${field.required ? 'yes' : 'no'} | ${field.unique ? 'yes' : 'no'} | ${cell([...field.enumValues].sort().join(', ') || '-')} |`,
          ),
          '',
        ]),
    '### Indexes',
    '',
    ...(indexes.length === 0
      ? ['なし', '']
      : [
          '| Name | Columns | Unique |',
          '| --- | --- | --- |',
          ...indexes.map(
            (index) =>
              `| ${cell(index.name)} | ${cell([...index.columns].sort().join(', '))} | ${index.unique ? 'yes' : 'no'} |`,
          ),
          '',
        ]),
    '### Relations',
    '',
    ...(relations.length === 0
      ? ['なし', '']
      : [
          '| Name | Type | Field | Target | References |',
          '| --- | --- | --- | --- | --- |',
          ...relations.map(
            (relation) =>
              `| ${cell(relation.name)} | ${cell(relation.type)} | ${cell(relation.field)} | ${cell(relation.targetModel)} | ${cell(relation.references)} |`,
          ),
          '',
        ]),
    '### API',
    '',
    apiSummary(model),
    '',
  ];
}

function apiSummary(model: Model): string {
  if (model.api.resource === null) return 'なし';
  const operations = [
    'list',
    ...(model.api.create ? ['create'] : []),
    ...(model.api.update ? ['update'] : []),
    ...(model.api.delete ? ['delete'] : []),
  ];
  return `Resource: \`${code(model.api.resource)}\`  \nOperations: ${operations.join(', ')}`;
}

function heading(value: string): string {
  return value
    .replaceAll('\\', '\\\\')
    .replaceAll('#', '\\#')
    .replaceAll('\n', ' ');
}

function text(value: string): string {
  return value.replaceAll('\\', '\\\\').replaceAll('\n', '<br>');
}

function cell(value: string): string {
  return text(value).replaceAll('|', '\\|');
}

function code(value: string): string {
  return value.replaceAll('`', '\\`').replaceAll('\n', ' ');
}
