import type { ApplicationModel, Field, Model } from '@gstack/application';

import type { GeneratedArtifactInput } from './artifact.js';
import { typescriptTypeName } from './typescript.js';

const HEADER = '// This file was generated by gstack. DO NOT EDIT.\n\n';

export function generateReactArtifacts(
  application: ApplicationModel,
): readonly GeneratedArtifactInput[] {
  const models = [...application.models].sort((left, right) =>
    left.name.localeCompare(right.name),
  );
  const outputs = models.flatMap((model) => [
    ...(model.ui.list.columns.length === 0 ? [] : [listArtifact(model)]),
    ...(model.ui.form.fields.length === 0 ? [] : [formArtifact(model)]),
  ]);
  return Object.freeze([...outputs, indexArtifact(outputs)]);
}

function listArtifact(model: Model): GeneratedArtifactInput {
  const name = typescriptTypeName(model.name);
  const headers = model.ui.list.columns
    .map((column) => `          <th scope="col">${escapeText(column)}</th>`)
    .join('\n');
  const cells = model.ui.list.columns
    .map(
      (column) =>
        `            <td>{String(item[${JSON.stringify(column)}] ?? '')}</td>`,
    )
    .join('\n');
  return Object.freeze({
    path: `generated/frontend/${model.name}/list.tsx`,
    content: `${HEADER}import type { ${name} } from '../../types/${model.name}.js';

export interface ${name}ListProps {
  readonly items: readonly ${name}[];
  readonly className?: string;
}

export function ${name}List({ items, className }: ${name}ListProps) {
  return (
    <table className={className}>
      <thead>
        <tr>
${headers}
        </tr>
      </thead>
      <tbody>
        {items.map((item) => (
          <tr key={String(item[${JSON.stringify(model.primaryKey)}])}>
${cells}
          </tr>
        ))}
      </tbody>
    </table>
  );
}
`,
  });
}

function formArtifact(model: Model): GeneratedArtifactInput {
  const name = typescriptTypeName(model.name);
  const fields = model.ui.form.fields
    .map((fieldName) => model.fields.find(({ name }) => name === fieldName)!)
    .map(formField)
    .join('\n');
  return Object.freeze({
    path: `generated/frontend/${model.name}/form.tsx`,
    content: `${HEADER}import type { FormEvent } from 'react';
import type { ${name} } from '../../types/${model.name}.js';

export type ${name}FormValue = { readonly [Key in keyof ${name}]: string | boolean };

export interface ${name}FormProps {
  readonly value: ${name}FormValue;
  readonly onChange: (value: ${name}FormValue) => void;
  readonly onSubmit: (value: ${name}FormValue) => void;
  readonly className?: string;
}

export function ${name}Form({ value, onChange, onSubmit, className }: ${name}FormProps) {
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    onSubmit(value);
  }
  return (
    <form className={className} onSubmit={submit}>
${fields}
      <button type="submit">Submit</button>
    </form>
  );
}
`,
  });
}

function formField(field: Field): string {
  const name = JSON.stringify(field.name);
  const label = escapeText(field.name);
  if (field.type === 'boolean') {
    return `      <label>${label}<input type="checkbox" checked={Boolean(value[${name}])} onChange={(event) => onChange({ ...value, [${name}]: event.currentTarget.checked })} /></label>`;
  }
  if (field.type === 'enum') {
    const options = field.enumValues
      .map(
        (item) =>
          `<option value=${JSON.stringify(item)}>${escapeText(item)}</option>`,
      )
      .join('');
    return `      <label>${label}<select value={String(value[${name}] ?? '')} onChange={(event) => onChange({ ...value, [${name}]: event.currentTarget.value })}>${options}</select></label>`;
  }
  if (field.type === 'text') {
    return `      <label>${label}<textarea value={String(value[${name}] ?? '')} onChange={(event) => onChange({ ...value, [${name}]: event.currentTarget.value })} /></label>`;
  }
  const type = inputType(field.type);
  return `      <label>${label}<input type=${JSON.stringify(type)} value={String(value[${name}] ?? '')} onChange={(event) => onChange({ ...value, [${name}]: event.currentTarget.value })} /></label>`;
}

function inputType(type: Field['type']): string {
  if (type === 'integer' || type === 'number') return 'number';
  if (type === 'date') return 'date';
  if (type === 'datetime') return 'datetime-local';
  return 'text';
}

function indexArtifact(
  outputs: readonly GeneratedArtifactInput[],
): GeneratedArtifactInput {
  const exports = outputs
    .map(({ path }) => {
      const match = /^generated\/frontend\/([^/]+)\/(list|form)\.tsx$/u.exec(
        path,
      )!;
      const component = `${typescriptTypeName(match[1]!)}${match[2] === 'list' ? 'List' : 'Form'}`;
      return `export { ${component} } from './${match[1]}/${match[2]}.js';`;
    })
    .join('\n');
  return Object.freeze({
    path: 'generated/frontend/index.ts',
    content: `${HEADER}${exports}${exports ? '\n' : ''}`,
  });
}

function escapeText(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;');
}
