import { describe, expect, it } from 'vitest';

import type { ApplicationModel, Field, Model } from '@gstack/application';

import { generateTypeArtifacts, typescriptTypeName } from './typescript.js';

const validation = {
  minLength: null,
  maxLength: null,
  pattern: null,
  min: null,
  max: null,
};

describe('Type Generator', () => {
  it('全Field typeを決定的なTypeScript interfaceへ変換する', () => {
    const fields: Field[] = [
      field('text_value', 'text'),
      field('string_value', 'string'),
      field('number_value', 'number'),
      field('integer_value', 'integer'),
      field('json_value', 'json'),
      field('uuid_value', 'uuid'),
      field('datetime_value', 'datetime'),
      field('date_value', 'date'),
      field('boolean_value', 'boolean'),
      field('role', 'enum', { enumValues: ['admin', 'member'] }),
      field('required_value', 'string', { required: true }),
    ];
    const [artifact] = generateTypeArtifacts(
      application([model('user_profile', fields)]),
    );

    expect(artifact).toEqual({
      path: 'generated/types/user_profile.ts',
      content: `// This file was generated by gstack. DO NOT EDIT.

export interface UserProfile {
  readonly "boolean_value"?: boolean;
  readonly "date_value"?: string;
  readonly "datetime_value"?: string;
  readonly "integer_value"?: number;
  readonly "json_value"?: unknown;
  readonly "number_value"?: number;
  readonly "required_value": string;
  readonly "role"?: "admin" | "member";
  readonly "string_value"?: string;
  readonly "text_value"?: string;
  readonly "uuid_value"?: string;
}
`,
    });
  });

  it('Modelをname順に生成しindexから再exportする', () => {
    const artifacts = generateTypeArtifacts(
      application([model('z_items', []), model('accounts', [])]),
    );
    expect(artifacts.map(({ path }) => path)).toEqual([
      'generated/types/accounts.ts',
      'generated/types/z_items.ts',
      'generated/types/index.ts',
    ]);
    expect(artifacts.at(-1)?.content).toContain(
      "export type { Accounts } from './accounts.js';\nexport type { ZItems } from './z_items.js';",
    );
  });

  it('snake_caseをPascalCaseへ変換する', () => {
    expect(typescriptTypeName('user_profile')).toBe('UserProfile');
  });
});

function field(
  name: string,
  type: Field['type'],
  overrides: Partial<Field> = {},
): Field {
  return {
    name,
    type,
    required: false,
    unique: false,
    enumValues: [],
    validation,
    ...overrides,
  };
}

function model(name: string, fields: readonly Field[]): Model {
  return {
    name,
    displayName: name,
    description: null,
    primaryKey: fields[0]?.name ?? 'id',
    fields,
    indexes: [],
    relations: [],
    api: { resource: null, create: false, update: false, delete: false },
    ui: { list: { columns: [] }, form: { fields: [] } },
    permissions: { read: [], create: [], update: [], delete: [] },
    workflow: { enabled: false },
    events: { enabled: false },
    metadata: {},
  };
}

function application(models: readonly Model[]): ApplicationModel {
  return { schemaVersion: 1, name: 'app', models, metadata: {} };
}
