import type { ApplicationModel, Field, Model } from '@gstack/application';

import type { GeneratedArtifactInput } from './artifact.js';

const HEADER = '// This file was generated by gstack. DO NOT EDIT.\n\n';

export function generateTypeArtifacts(
  application: ApplicationModel,
): readonly GeneratedArtifactInput[] {
  const models = [...application.models].sort((left, right) =>
    left.name.localeCompare(right.name),
  );
  return Object.freeze([
    ...models.map(generateModelType),
    generateTypeIndex(models),
  ]);
}

export function typescriptTypeName(modelName: string): string {
  return modelName
    .split('_')
    .map((part) => `${part[0]!.toUpperCase()}${part.slice(1)}`)
    .join('');
}

function generateModelType(model: Model): GeneratedArtifactInput {
  const fields = [...model.fields].sort((left, right) =>
    left.name.localeCompare(right.name),
  );
  const body = fields
    .map(
      (field) =>
        `  readonly ${JSON.stringify(field.name)}${field.required ? '' : '?'}: ${fieldType(field)};`,
    )
    .join('\n');
  return Object.freeze({
    path: `generated/types/${model.name}.ts`,
    content: `${HEADER}export interface ${typescriptTypeName(model.name)} {\n${body}\n}\n`,
  });
}

function generateTypeIndex(models: readonly Model[]): GeneratedArtifactInput {
  const exports = models
    .map(
      (model) =>
        `export type { ${typescriptTypeName(model.name)} } from './${model.name}.js';`,
    )
    .join('\n');
  return Object.freeze({
    path: 'generated/types/index.ts',
    content: `${HEADER}${exports}${exports ? '\n' : ''}`,
  });
}

function fieldType(field: Field): string {
  switch (field.type) {
    case 'string':
    case 'text':
    case 'uuid':
    case 'date':
    case 'datetime':
      return 'string';
    case 'integer':
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'json':
      return 'unknown';
    case 'enum':
      return field.enumValues.map((value) => JSON.stringify(value)).join(' | ');
  }
}
