import type { ApplicationModel, Field, Model } from '@gstack/application';

import type { GeneratedArtifactInput } from './artifact.js';
import { typescriptTypeName } from './typescript.js';

const HEADER = '// This file was generated by gstack. DO NOT EDIT.\n\n';

export function generateValidationArtifacts(
  application: ApplicationModel,
): readonly GeneratedArtifactInput[] {
  const models = [...application.models].sort((left, right) =>
    left.name.localeCompare(right.name),
  );
  return Object.freeze([
    runtimeArtifact(),
    ...models.map(modelArtifact),
    indexArtifact(models),
  ]);
}

function modelArtifact(model: Model): GeneratedArtifactInput {
  const typeName = typescriptTypeName(model.name);
  const rules = [...model.fields]
    .sort((left, right) => left.name.localeCompare(right.name))
    .map(fieldRule)
    .join(',\n');
  return Object.freeze({
    path: `generated/validation/${model.name}.ts`,
    content: `${HEADER}import type { ${typeName} } from '../types/${model.name}.js';
import { validateObject, type ValidationResult } from './runtime.js';

const rules = [
${rules}
] as const;

export function validate${typeName}(value: unknown): ValidationResult<${typeName}> {
  return validateObject<${typeName}>(value, rules);
}
`,
  });
}

function fieldRule(field: Field): string {
  const validation = field.validation;
  const values = [
    `name: ${JSON.stringify(field.name)}`,
    `type: ${JSON.stringify(field.type)}`,
    `required: ${String(field.required)}`,
    ...(field.type === 'enum'
      ? [`enumValues: ${JSON.stringify([...field.enumValues].sort())}`]
      : []),
    ...(validation.minLength === null
      ? []
      : [`minLength: ${String(validation.minLength)}`]),
    ...(validation.maxLength === null
      ? []
      : [`maxLength: ${String(validation.maxLength)}`]),
    ...(validation.pattern === null
      ? []
      : [`pattern: ${JSON.stringify(validation.pattern)}`]),
    ...(validation.min === null ? [] : [`min: ${String(validation.min)}`]),
    ...(validation.max === null ? [] : [`max: ${String(validation.max)}`]),
  ];
  return `  { ${values.join(', ')} }`;
}

function indexArtifact(models: readonly Model[]): GeneratedArtifactInput {
  const exports = models
    .map(
      (model) =>
        `export { validate${typescriptTypeName(model.name)} } from './${model.name}.js';`,
    )
    .join('\n');
  return Object.freeze({
    path: 'generated/validation/index.ts',
    content: `${HEADER}export type { ValidationIssue, ValidationResult } from './runtime.js';\n${exports}${exports ? '\n' : ''}`,
  });
}

function runtimeArtifact(): GeneratedArtifactInput {
  return Object.freeze({
    path: 'generated/validation/runtime.ts',
    content: `${HEADER}export interface ValidationIssue {
  readonly path: string;
  readonly code: 'VALIDATION_OBJECT_REQUIRED' | 'VALIDATION_REQUIRED' | 'VALIDATION_TYPE' | 'VALIDATION_ENUM' | 'VALIDATION_MIN_LENGTH' | 'VALIDATION_MAX_LENGTH' | 'VALIDATION_PATTERN' | 'VALIDATION_MIN' | 'VALIDATION_MAX';
  readonly message: string;
}

export type ValidationResult<T> =
  | { readonly valid: true; readonly value: T; readonly issues: readonly [] }
  | { readonly valid: false; readonly value: null; readonly issues: readonly ValidationIssue[] };

interface FieldRule {
  readonly name: string;
  readonly type: 'string' | 'text' | 'integer' | 'number' | 'boolean' | 'uuid' | 'date' | 'datetime' | 'json' | 'enum';
  readonly required: boolean;
  readonly enumValues?: readonly string[];
  readonly minLength?: number;
  readonly maxLength?: number;
  readonly pattern?: string;
  readonly min?: number;
  readonly max?: number;
}

export function validateObject<T>(value: unknown, rules: readonly FieldRule[]): ValidationResult<T> {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    return { valid: false, value: null, issues: [{ path: '$', code: 'VALIDATION_OBJECT_REQUIRED', message: 'Value must be an object.' }] };
  }
  const input = value as Record<string, unknown>;
  const issues: ValidationIssue[] = [];
  for (const rule of rules) validateField(input[rule.name], rule, issues);
  return issues.length === 0
    ? { valid: true, value: value as T, issues: [] }
    : { valid: false, value: null, issues };
}

function validateField(value: unknown, rule: FieldRule, issues: ValidationIssue[]): void {
  if (value === undefined) {
    if (rule.required) issue(issues, rule.name, 'VALIDATION_REQUIRED', 'Field is required.');
    return;
  }
  if (!validType(value, rule.type)) {
    issue(issues, rule.name, 'VALIDATION_TYPE', 'Field has an invalid type.');
    return;
  }
  if (rule.enumValues && !rule.enumValues.includes(value as string)) issue(issues, rule.name, 'VALIDATION_ENUM', 'Field is not an allowed Enum value.');
  if (typeof value === 'string') {
    if (rule.minLength !== undefined && value.length < rule.minLength) issue(issues, rule.name, 'VALIDATION_MIN_LENGTH', 'Field is shorter than minLength.');
    if (rule.maxLength !== undefined && value.length > rule.maxLength) issue(issues, rule.name, 'VALIDATION_MAX_LENGTH', 'Field is longer than maxLength.');
    if (rule.pattern !== undefined && !new RegExp(rule.pattern, 'u').test(value)) issue(issues, rule.name, 'VALIDATION_PATTERN', 'Field does not match pattern.');
  }
  if (typeof value === 'number') {
    if (rule.min !== undefined && value < rule.min) issue(issues, rule.name, 'VALIDATION_MIN', 'Field is less than min.');
    if (rule.max !== undefined && value > rule.max) issue(issues, rule.name, 'VALIDATION_MAX', 'Field is greater than max.');
  }
}

function validType(value: unknown, type: FieldRule['type']): boolean {
  if (type === 'integer') return typeof value === 'number' && Number.isFinite(value) && Number.isInteger(value);
  if (type === 'number') return typeof value === 'number' && Number.isFinite(value);
  if (type === 'boolean') return typeof value === 'boolean';
  if (type === 'json') return validJson(value);
  return typeof value === 'string';
}

function validJson(value: unknown, seen = new Set<object>()): boolean {
  if (value === null || typeof value === 'string' || typeof value === 'boolean') return true;
  if (typeof value === 'number') return Number.isFinite(value);
  if (typeof value !== 'object' || seen.has(value)) return false;
  seen.add(value);
  if (Array.isArray(value)) return value.every((item) => validJson(item, seen));
  if (Object.getPrototypeOf(value) !== Object.prototype) return false;
  return Object.values(value as Record<string, unknown>).every((item) => validJson(item, seen));
}

function issue(issues: ValidationIssue[], path: string, code: ValidationIssue['code'], message: string): void {
  issues.push({ path, code, message });
}
`,
  });
}
